### ISSUE TITLE
Firefox password import (from csv)

### ISSUE THREAD

**Issue by piotrowskiadam** [Rabbit-Company/Passky-Desktop#8]
Firefox password import (from csv) would allow users who used to use firefox as their password manager to move to Passky.
Firefox allows only to export passwords as csv file so Passky would need to support import from csv.

**Comment by zigazajc007** [comment]
Thanks, I have added it to the TO DO list and it will be included in next update.

**Comment by zigazajc007** [comment]
This feature has been added in Passky v6.1.0
