### ISSUE TITLE
Why are You forcing usernames to not contain special characters?

### ISSUE THREAD

**Issue by RDKRACZ** [Rabbit-Company/Passky-Desktop#9]
I use `_` and `-` in my usernames...

**Comment by zigazajc007** [comment]
So users won't use emojis, Arabic, Chinese characters... in their username.

_ and - are quite common in usernames, so I can add those two.

You can expect support for those 2 characters in next update.

**Comment by zigazajc007** [comment]
Passky has been updated to v7.0.0.

This version now support underscore character.
